extends SceneTree
## Renders pseudo-3D unit sprites (EW-style figures seen from above at an angle)
## into assets/units/<name>_<dir>.png, one per hex direction (0 = east, then
## counter-clockwise in 60 degree steps, matching Hex.DIRS), plus <name>.json
## with the ground anchor.
## A model is either a procedural builder (tools/models/*.gd) or a ready-made
## glTF/FBX file (.glb/.gltf/.fbx, e.g. from a 3D stock site or an AI generator)
## that is scaled to real size and turned to face +X. Team colour is not baked in: the game draws a
## coloured base ring under each unit.
##
## Needs a GPU context, e.g.:
##   xvfb-run godot --path . --rendering-method forward_plus -s res://tools/render_units.gd [-- t72]
## One-off render of a downloaded model (writes assets/units/<name>.png):
##   ... -s res://tools/render_units.gd -- --name=t72 --file=/path/t72.glb --length=9.5 --yaw=0
## Large preview image instead of the game sprite: add --preview=/path/out.png
## Try another camera angle: --elevation=55 (degrees above the horizon)
## Untextured "clay" preview with every named part in its own colour: --clay=1
##
## Models with a "turret" entry are rendered as two layers so the game can turn
## the turret on its own: <name>_hull_<i>.png (hull and running gear) and
## <name>_turret_<i>.png (turret and gun, with the turret's shadow on the deck),
## LAYER_FRAMES of each, i * 360 / LAYER_FRAMES degrees counter-clockwise from
## east on the map. The JSON gives both anchors and, per hull frame, where the
## turret pivot lands relative to the hull anchor.

const SUPERSAMPLE := 4
const OUT_SIZE := Vector2i(320, 320)  # square: a vehicle may point any way
const DIRECTIONS := 6
const LAYER_FRAMES := 36  # 10 degree steps for smooth hull and turret turns
const PX_PER_M := 320.0 / 11.0  # sprite scale shared by every layer
const HULL_SIZE := Vector2i(320, 320)
const TURRET_SIZE := Vector2i(416, 416)  # the gun reaches ~6 m from the turret pivot
const OUT_DIR := "res://assets/units/"
## file: builder script or glTF; length_m: real length (glTF is scaled to it);
## yaw: extra turn in degrees so the glTF's front points to +X;
## roughness: matte level for imported paint (EW-style figures are matte);
## tint: multiplies the paint colour (e.g. to darken a pale texture);
## weathered: add mud, dust, streaks and chipped paint (tools/models/weathered.gdshader);
## paint: our own paint instead of the file's textures, per part-name prefix:
##   {"Hull": {"color": Color}, "Wheel": {"color": Color, "tyre": radius_m}, "Track": {"color": Color, "links": true}};
##   "detail"/"detail_rect": top-down relief map painted over the part (model x0, z0, x1, z1);
##   "no_shadow": the part does not receive sun shadows (only soft occlusion), so
##   running gear under the fenders stays readable ("lift": extra light, default 0.45);
## no_cast: part-name prefixes that cast no shadow at all (e.g. the gun);
## mud_height: how high (m) mud reaches on painted models;
## turret: {"parts": name prefixes that turn, "pivot": [x, z] ring centre in file units};
## hull_offset_m: how far the hull centre sits behind the model centre (a long gun
## shifts the model centre forward); the game uses it to centre the hull on a hex.
const MODELS := {
	# Generated by the owner in Meshy AI; the texture is pale sage, tinted to olive.
	"t72": {"file": "res://tools/source_models/t72_meshy.fbx", "length_m": 9.5, "yaw": 180.0,
		"tint": Color(0.5, 0.56, 0.4), "weathered": true, "hull_offset_m": 1.3},
	"t72_procedural": {"file": "res://tools/models/t72.gd"},
	# From "Rambo: The Video Game" (via p3dm.ru): personal use only, not for publishing.
	# Own paint and weathering; forward is -X in the file, 9.35 m with the gun
	# (rear fuel drums and unditching log removed by tools/source_models/convert_t72_rambo.py).
	"t72_rambo": {"file": "res://tools/source_models/t72_rambo.glb", "length_m": 9.35, "yaw": 180.0,
		"hull_offset_m": 1.35, "mud_height": 1.1, "no_cast": ["Gun"],
		"turret": {"parts": ["Turret", "Gun"], "pivot": [0.25, 0.03]},  # pivot: turret ring centre, file x/z
		"paint": {
			"HullLower": {"color": Color(0.15, 0.145, 0.12)},  # lower hull sides and stern plate
			"Hull": {"color": Color(0.20, 0.205, 0.18), "detail": "res://tools/models/t72_hull_detail.png",
				"detail_rect": [-3.2, -1.85, 3.7, 1.85]},
			"Turret": {"color": Color(0.20, 0.205, 0.18)},
			"Gun": {"color": Color(0.20, 0.205, 0.18)},
			"Wheel": {"color": Color(0.19, 0.185, 0.155), "tyre": 0.29, "no_shadow": true},
			"Sprocket": {"color": Color(0.20, 0.21, 0.17), "no_shadow": true},
			"Idler": {"color": Color(0.20, 0.21, 0.17), "no_shadow": true},
			"Track": {"color": Color(0.24, 0.22, 0.19), "links": true, "no_shadow": true},
		}},
}
const ELEVATION := 65.0  # camera angle above the horizon
const VIEW_HEIGHT_M := 11.0  # metres visible vertically
const LOOK_AT := Vector3(0, 0.8, 0)
## Sun on the map: azimuth clockwise from north (45 = north-east) and height
## above the horizon. It is fixed to the map, so in every facing the model is
## lit and casts its ground shadow the same way (here towards the south-west).
const SUN_AZIMUTH := 45.0
const SUN_ELEVATION := 75.0

var preview_path := ""
var ground: MeshInstance3D
var sun_light: DirectionalLight3D
var fill_light: DirectionalLight3D
var world_env: Environment
const SHADOW_OPACITY := 0.6  # darkness of the ground shadow baked into sprites
var clay := false
var weathering := -1.0  # --weathering=0..1 overrides the model's amount (0 = clean paint)
var elevation := ELEVATION


func _initialize() -> void:
	_run.call_deferred()


func _run() -> void:
	var only: Array[String] = []
	var models := MODELS.duplicate()
	var opts := {}
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--") and "=" in a:
			opts[a.substr(2).get_slice("=", 0)] = a.get_slice("=", 1)
		else:
			only.append(a)
	if opts.has("file"):
		var n: String = opts.get("name", opts["file"].get_file().get_basename())
		models[n] = {"file": opts["file"], "length_m": float(opts.get("length", "7.0")),
			"yaw": float(opts.get("yaw", "0")), "roughness": float(opts.get("roughness", "0.85")),
			"tint": Color(opts.get("tint", "ffffff")), "weathered": opts.get("weathered", "0") == "1"}
		only = [n]
	preview_path = opts.get("preview", "")
	clay = opts.get("clay", "0") == "1"
	weathering = float(opts.get("weathering", "-1"))
	var vp := SubViewport.new()
	vp.size = OUT_SIZE * SUPERSAMPLE
	vp.transparent_bg = true
	vp.own_world_3d = true
	vp.msaa_3d = Viewport.MSAA_4X
	vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(vp)

	var cam := Camera3D.new()
	cam.projection = Camera3D.PROJECTION_ORTHOGONAL
	cam.size = VIEW_HEIGHT_M
	elevation = float(opts.get("elevation", str(ELEVATION)))
	var e := deg_to_rad(elevation)
	cam.position = Vector3(0, sin(e), cos(e)) * 30.0 + LOOK_AT
	vp.add_child(cam)
	cam.look_at(LOOK_AT)

	var sun := DirectionalLight3D.new()
	# Key light from the upper left, in front of the model.
	sun.light_energy = 2.3
	sun.light_color = Color(1.0, 0.95, 0.85)
	# Scene axes: east = +X, north = -Z (the camera looks from the south), up = +Y.
	var az := deg_to_rad(float(opts.get("sun_az", str(SUN_AZIMUTH))))
	var el := deg_to_rad(float(opts.get("sun_el", str(SUN_ELEVATION))))
	var to_sun := Vector3(cos(el) * sin(az), sin(el), -cos(el) * cos(az))
	vp.add_child(sun)
	sun.look_at_from_position(to_sun * 20.0, Vector3.ZERO)
	sun.shadow_enabled = true
	sun.shadow_blur = 0.4  # crisp shadows so small parts read
	sun.shadow_bias = 0.03
	sun.shadow_normal_bias = 1.0  # enough against striped self-shadowing, small parts still cast
	sun.directional_shadow_mode = DirectionalLight3D.SHADOW_PARALLEL_4_SPLITS
	sun.directional_shadow_max_distance = 100.0
	var fill := DirectionalLight3D.new()
	fill.light_energy = 0.4
	fill.light_color = Color(0.75, 0.82, 1.0)
	fill.rotation_degrees = Vector3(-25, 150, 0)
	vp.add_child(fill)

	var env := Environment.new()
	env.background_mode = Environment.BG_CLEAR_COLOR
	var sky := Sky.new()
	sky.sky_material = ProceduralSkyMaterial.new()
	env.sky = sky
	env.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	env.ambient_light_energy = 0.32
	env.tonemap_mode = Environment.TONE_MAPPER_FILMIC
	env.tonemap_exposure = 1.05
	env.ssao_enabled = true
	# Strong, tight ambient occlusion darkens seams, hatches and grilles.
	env.ssao_radius = 0.25
	env.ssao_intensity = 7.0
	env.ssao_power = 2.2
	env.ssao_detail = 1.0
	env.ssao_light_affect = 0.25
	env.adjustment_enabled = true
	env.adjustment_saturation = 0.95
	env.adjustment_contrast = 1.12
	var we := WorldEnvironment.new()
	we.environment = env
	vp.add_child(we)

	# Ground used only in the shadow pass: white, lit by the sun alone, so its
	# brightness drop is the model's cast shadow (see _render).
	ground = MeshInstance3D.new()
	var plane := PlaneMesh.new()
	plane.size = Vector2(60, 60)
	ground.mesh = plane
	var gm := StandardMaterial3D.new()
	gm.albedo_color = Color.WHITE
	gm.roughness = 1.0
	ground.material_override = gm
	ground.visible = false
	vp.add_child(ground)
	sun_light = sun
	fill_light = fill
	world_env = env

	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	for model_name in models:
		if only.is_empty() or model_name in only:
			await _render(vp, cam, model_name, models[model_name])
	quit()


func _render(vp: SubViewport, cam: Camera3D, model_name: String, spec: Dictionary) -> void:
	var file: String = spec["file"]
	var model := Node3D.new()
	vp.add_child(model)
	if file.ends_with(".gd"):
		load(file).new().build(model)
	else:
		_add_gltf(model, file, spec.get("length_m", 7.0), spec.get("yaw", 0.0))
		if spec.has("paint"):
			_paint(model, spec["paint"], weathering if weathering >= 0.0 else float(spec.get("weathering", 1.0)),
				float(spec.get("mud_height", 1.45)))
		else:
			_fix_materials(model, spec.get("roughness", 0.85), spec.get("tint", Color.WHITE),
				spec.get("weathered", false))
		if clay:
			_clay_materials(model)
	for prefix in spec.get("no_cast", []):
		for g in model.find_children(prefix + "*", "GeometryInstance3D", true, false):
			(g as GeometryInstance3D).cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
			g.set_meta("no_cast", true)
	var base := ProjectSettings.globalize_path(OUT_DIR + model_name)
	if spec.has("turret") and preview_path == "":
		await _render_layers(vp, cam, model, base, spec)
		model.queue_free()
		return
	var frames: Array[Image] = []
	for d in DIRECTIONS:
		model.rotation_degrees.y = _yaw_for_dir(d)
		for i in 4:
			await RenderingServer.frame_post_draw
		var img := vp.get_texture().get_image()
		img.resize(OUT_SIZE.x, OUT_SIZE.y, Image.INTERPOLATE_LANCZOS)
		var shadow := await _shadow_pass(vp, model)
		img = _under_shadow(img, shadow)
		frames.append(img)
		if preview_path == "":
			img.save_png("%s_%d.png" % [base, d])
	model.queue_free()
	if preview_path != "":
		_save_preview(frames)
		return
	# Where the model's ground origin lands in the sprite, and its scale.
	var anchor := cam.unproject_position(Vector3.ZERO) / SUPERSAMPLE
	var meta := {"anchor": [anchor.x, anchor.y], "px_per_m": OUT_SIZE.y / VIEW_HEIGHT_M,
		"directions": DIRECTIONS, "elevation": elevation, "hull_offset_m": spec.get("hull_offset_m", 0.0)}
	var f := FileAccess.open(base + ".json", FileAccess.WRITE)
	f.store_string(JSON.stringify(meta))
	print("rendered ", base, "_0..", DIRECTIONS - 1, ".png  anchor=", anchor)


## Hull and turret layers (see the header). The turret parts are moved under a
## pivot at the turret ring; the hull layer hides them, the turret layer hides
## the hull and catches the turret's shadow on a plane at deck height.
func _render_layers(vp: SubViewport, cam: Camera3D, model: Node3D, base: String, spec: Dictionary) -> void:
	var tspec: Dictionary = spec["turret"]
	var first: MeshInstance3D = model.find_children("Hull*", "MeshInstance3D", true, false)[0]
	var scene_root: Node3D = first.get_parent()
	var pivot := Node3D.new()
	pivot.position = Vector3(tspec["pivot"][0], 0.0, tspec["pivot"][1])
	scene_root.add_child(pivot)
	var turret_parts: Array[GeometryInstance3D] = []
	var hull_parts: Array[GeometryInstance3D] = []
	for g in model.find_children("*", "GeometryInstance3D", true, false):
		var is_turret := false
		for prefix in tspec["parts"]:
			if String(g.name).begins_with(prefix):
				is_turret = true
		if is_turret:
			g.reparent(pivot, true)
			turret_parts.append(g)
		else:
			hull_parts.append(g)
	var deck_y := INF
	for g in turret_parts:
		var box: AABB = g.global_transform * (g as MeshInstance3D).get_aabb()
		deck_y = minf(deck_y, box.position.y)

	var offsets := []
	_set_layer_size(vp, cam, HULL_SIZE)
	for g in turret_parts:
		g.visible = false
	for i in LAYER_FRAMES:
		model.rotation_degrees.y = _yaw_for_angle(360.0 * i / LAYER_FRAMES)
		var img := await _layer_frame(vp, model, HULL_SIZE, 0.0)
		img.save_png("%s_hull_%d.png" % [base, i])
		var p := pivot.global_position
		var d := (cam.unproject_position(Vector3(p.x, 0.0, p.z)) - cam.unproject_position(Vector3.ZERO)) / SUPERSAMPLE
		offsets.append([d.x, d.y])
	var hull_anchor := cam.unproject_position(Vector3.ZERO) / SUPERSAMPLE

	_set_layer_size(vp, cam, TURRET_SIZE)
	for g in turret_parts:
		g.visible = true
	for g in hull_parts:
		g.visible = false
	for i in LAYER_FRAMES:
		model.position = Vector3.ZERO
		model.rotation_degrees.y = _yaw_for_angle(360.0 * i / LAYER_FRAMES)
		var p := pivot.global_position
		model.position = Vector3(-p.x, 0.0, -p.z)  # turret pivot on the frame's ground anchor
		var img := await _layer_frame(vp, model, TURRET_SIZE, deck_y)
		img.save_png("%s_turret_%d.png" % [base, i])
	var turret_anchor := cam.unproject_position(Vector3.ZERO) / SUPERSAMPLE
	_set_layer_size(vp, cam, OUT_SIZE)

	var meta := {"layers": true, "frames": LAYER_FRAMES, "px_per_m": PX_PER_M, "elevation": elevation,
		"hull_offset_m": spec.get("hull_offset_m", 0.0),
		"hull_anchor": [hull_anchor.x, hull_anchor.y], "turret_anchor": [turret_anchor.x, turret_anchor.y],
		"turret_offsets": offsets}
	var f := FileAccess.open(base + ".json", FileAccess.WRITE)
	f.store_string(JSON.stringify(meta))
	print("rendered ", base, " hull/turret x", LAYER_FRAMES)


func _set_layer_size(vp: SubViewport, cam: Camera3D, size: Vector2i) -> void:
	vp.size = size * SUPERSAMPLE
	cam.size = size.y / PX_PER_M


func _layer_frame(vp: SubViewport, model: Node3D, size: Vector2i, ground_y: float) -> Image:
	for i in 4:
		await RenderingServer.frame_post_draw
	var img := vp.get_texture().get_image()
	img.resize(size.x, size.y, Image.INTERPOLATE_LANCZOS)
	var shadow := await _shadow_pass(vp, model, ground_y)
	return _under_shadow(img, shadow)


## Map heading (degrees counter-clockwise from east) -> model yaw, corrected for
## the tilted camera like _yaw_for_dir.
func _yaw_for_angle(deg: float) -> float:
	var a := deg_to_rad(deg)
	return rad_to_deg(atan2(sin(a) / sin(deg_to_rad(elevation)), cos(a)))


## Renders the model's cast shadow on a white ground (at ground_y) lit by the
## sun alone and returns it at output size as shadow strength (L8, 255 = full).
func _shadow_pass(vp: SubViewport, model: Node3D, ground_y := 0.0) -> Image:
	var saved := []
	for g in model.find_children("*", "GeometryInstance3D", true, false):
		saved.append([g, g.visible, g.cast_shadow])
		if g.visible:
			(g as GeometryInstance3D).cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_SHADOWS_ONLY
			if g.has_meta("no_cast"):
				g.visible = false
	ground.position.y = ground_y
	ground.visible = true
	fill_light.visible = false
	var ambient := world_env.ambient_light_energy
	var ssao := world_env.ssao_enabled
	world_env.ambient_light_energy = 0.0
	world_env.ssao_enabled = false
	world_env.tonemap_mode = Environment.TONE_MAPPER_LINEAR
	world_env.adjustment_enabled = false
	for i in 4:
		await RenderingServer.frame_post_draw
	var img := vp.get_texture().get_image()
	img.resize(vp.size.x / SUPERSAMPLE, vp.size.y / SUPERSAMPLE, Image.INTERPOLATE_LANCZOS)
	for sv in saved:
		sv[0].visible = sv[1]
		sv[0].cast_shadow = sv[2]
	ground.visible = false
	ground.position.y = 0.0
	fill_light.visible = true
	world_env.ambient_light_energy = ambient
	world_env.ssao_enabled = ssao
	world_env.tonemap_mode = Environment.TONE_MAPPER_FILMIC
	world_env.adjustment_enabled = true
	# Lit ground level = the brightest pixel; shadow = relative darkening.
	img.convert(Image.FORMAT_RGBA8)
	var lit := 0.0
	var w := img.get_width()
	var h := img.get_height()
	for y in range(0, h, 4):
		for x in range(0, w, 4):
			lit = maxf(lit, img.get_pixel(x, y).get_luminance())
	var out := Image.create(w, h, false, Image.FORMAT_L8)
	for y in h:
		for x in w:
			var v := clampf(1.0 - img.get_pixel(x, y).get_luminance() / maxf(lit, 0.001), 0.0, 1.0)
			out.set_pixel(x, y, Color(v, v, v))
	return out


## Model image over a translucent black shadow layer.
func _under_shadow(model_img: Image, shadow: Image) -> Image:
	model_img.convert(Image.FORMAT_RGBA8)
	var out := Image.create(model_img.get_width(), model_img.get_height(), false, Image.FORMAT_RGBA8)
	for y in out.get_height():
		for x in out.get_width():
			var sa := shadow.get_pixel(x, y).r * SHADOW_OPACITY
			var m := model_img.get_pixel(x, y)
			var a := m.a + sa * (1.0 - m.a)
			if a <= 0.0:
				continue
			var rgb := Color(m.r, m.g, m.b) * (m.a / a)  # shadow colour is black
			out.set_pixel(x, y, Color(rgb.r, rgb.g, rgb.b, a))
	return out


## Hex direction d points 60*d degrees counter-clockwise from screen-right on the
## flat map. The camera is tilted, so depth is foreshortened by sin(elevation);
## turn the model so its projected heading matches the map direction exactly.
func _yaw_for_dir(d: int) -> float:
	var a := deg_to_rad(60.0 * d)
	return rad_to_deg(atan2(sin(a) / sin(deg_to_rad(elevation)), cos(a)))


## All directions side by side on one image (3 per row), at double size.
func _save_preview(frames: Array[Image]) -> void:
	var w := OUT_SIZE.x * 2
	var h := OUT_SIZE.y * 2
	var sheet := Image.create(w * 3, h * 2, false, Image.FORMAT_RGBA8)
	var order := [2, 1, 0, 3, 4, 5]  # NW NE E / W SW SE reads like a compass
	for i in order.size():
		var img: Image = frames[order[i]].duplicate()
		img.resize(w, h, Image.INTERPOLATE_LANCZOS)
		sheet.blit_rect(img, Rect2i(Vector2i.ZERO, img.get_size()), Vector2i((i % 3) * w, (i / 3) * h))
	sheet.save_png(preview_path)
	print("preview ", preview_path)


## Loads a glTF/FBX, sets it on the ground centred at the origin and scales it so
## its longest horizontal side equals length_m.
func _add_gltf(parent: Node3D, file: String, length_m: float, yaw: float) -> void:
	var fbx := file.get_extension().to_lower() == "fbx"
	var doc: GLTFDocument = FBXDocument.new() if fbx else GLTFDocument.new()
	var state: GLTFState = FBXState.new() if fbx else GLTFState.new()
	var err := doc.append_from_file(ProjectSettings.globalize_path(file), state)
	assert(err == OK, "cannot load " + file)
	var scene := doc.generate_scene(state) as Node3D
	_bake_importer_meshes(scene)
	var pivot := Node3D.new()
	pivot.rotation_degrees.y = yaw
	parent.add_child(pivot)
	pivot.add_child(scene)
	var box := _bounds(parent)
	var s := length_m / maxf(box.size.x, box.size.z)
	pivot.scale = Vector3.ONE * s
	box = _bounds(parent)
	pivot.position -= Vector3(box.get_center().x, box.position.y, box.get_center().z)


## Generated/exported models often arrive with emission and vertex-colour tint
## switched on, which washes the paint out; turn those off and make paint matte.
func _fix_materials(model: Node3D, roughness: float, tint: Color, weathered: bool) -> void:
	for mi in model.find_children("*", "MeshInstance3D", true, false):
		var mesh: Mesh = (mi as MeshInstance3D).mesh
		for i in mesh.get_surface_count():
			var m := mesh.surface_get_material(i) as StandardMaterial3D
			if m == null:
				continue
			if weathered:
				(mi as MeshInstance3D).set_surface_override_material(i, _weathered(m, tint))
				continue
			m.emission_enabled = false
			m.vertex_color_use_as_albedo = false
			m.roughness_texture = null
			m.roughness = roughness
			m.metallic = 0.0
			m.albedo_color = tint


func _weathered(src: StandardMaterial3D, tint: Color) -> ShaderMaterial:
	var sm := ShaderMaterial.new()
	sm.shader = load("res://tools/models/weathered.gdshader")
	sm.set_shader_parameter("albedo_tex", src.albedo_texture)
	var lin := tint.srgb_to_linear()  # match StandardMaterial3D, whose albedo_color is sRGB
	sm.set_shader_parameter("tint", Vector3(lin.r, lin.g, lin.b))
	if src.normal_enabled and src.normal_texture:
		sm.set_shader_parameter("normal_tex", src.normal_texture)
		sm.set_shader_parameter("has_normal", true)
	sm.set_shader_parameter("noise_lo", _noise_tex(11, 0.012, 4))
	sm.set_shader_parameter("noise_hi", _noise_tex(12, 0.05, 5))
	return sm


func _noise_tex(seed_value: int, freq: float, octaves: int) -> ImageTexture:
	var n := FastNoiseLite.new()
	n.seed = seed_value
	n.frequency = freq
	n.fractal_octaves = octaves
	var img := n.get_seamless_image(512, 512)
	img.generate_mipmaps()
	return ImageTexture.create_from_image(img)


## Our own paint: one weathered-shader material per part, chosen by name prefix.
func _paint(model: Node3D, paint: Dictionary, amount: float, mud_height: float) -> void:
	for mi in model.find_children("*", "MeshInstance3D", true, false):
		var part := String(mi.name)
		var spec: Dictionary = {}
		var best := ""
		for key in paint:
			if part.begins_with(key) and key.length() > best.length():  # "HullLower" beats "Hull"
				best = key
				spec = paint[key]
		if spec.is_empty():
			continue
		var sm := ShaderMaterial.new()
		sm.shader = _weathered_shader(spec.get("no_shadow", false))
		var lin: Color = (spec["color"] as Color).srgb_to_linear()
		sm.set_shader_parameter("has_albedo", false)
		sm.set_shader_parameter("base_color", Vector3(lin.r, lin.g, lin.b))
		sm.set_shader_parameter("noise_lo", _noise_tex(11, 0.012, 4))
		sm.set_shader_parameter("noise_hi", _noise_tex(12, 0.05, 5))
		sm.set_shader_parameter("mud_height", mud_height)  # keep mud off low hull tops
		if spec.get("no_shadow", false):
			sm.set_shader_parameter("lift", float(spec.get("lift", 0.45)))
		if spec.has("tyre"):
			var box: AABB = (mi as MeshInstance3D).get_aabb()
			sm.set_shader_parameter("rubber_tyre", true)
			sm.set_shader_parameter("wheel_center", box.get_center())
			sm.set_shader_parameter("tyre_radius", spec["tyre"])
		if spec.has("detail"):
			var r: Array = spec["detail_rect"]
			sm.set_shader_parameter("has_detail", true)
			sm.set_shader_parameter("detail_tex", ImageTexture.create_from_image(
				Image.load_from_file(ProjectSettings.globalize_path(spec["detail"]))))
			sm.set_shader_parameter("detail_rect", Vector4(r[0], r[1], r[2], r[3]))
		if spec.get("links", false):
			sm.set_shader_parameter("track_links", true)
		var amounts := {"mud_amount": 0.85, "dust_amount": 0.3, "chip_amount": 0.8, "streak_amount": 0.7}
		for p in amounts:
			sm.set_shader_parameter(p, amounts[p] * amount)
		for i in (mi as MeshInstance3D).mesh.get_surface_count():
			(mi as MeshInstance3D).set_surface_override_material(i, sm)


var _shaders := {}


func _weathered_shader(no_shadow: bool) -> Shader:
	if not _shaders.has(no_shadow):
		var sh: Shader = load("res://tools/models/weathered.gdshader")
		if no_shadow:
			var copy := Shader.new()
			copy.code = sh.code.replace("render_mode diffuse_burley, cull_disabled;",
				"render_mode diffuse_burley, cull_disabled, shadows_disabled;")
			sh = copy
		_shaders[no_shadow] = sh
	return _shaders[no_shadow]


## Colour parts by name so the split (hull, turret, gun, running gear) is visible.
func _clay_materials(model: Node3D) -> void:
	var colors := {"Hull": Color(0.75, 0.72, 0.65), "Turret": Color(0.45, 0.62, 0.85), "Gun": Color(0.9, 0.4, 0.3),
		"Track": Color(0.3, 0.3, 0.3), "Wheel": Color(0.95, 0.8, 0.35), "Sprocket": Color(0.6, 0.85, 0.5),
		"Idler": Color(0.75, 0.5, 0.85)}
	for mi in model.find_children("*", "MeshInstance3D", true, false):
		var col := Color(0.8, 0.8, 0.8)
		for key in colors:
			if String(mi.name).begins_with(key) or String(mi.get_parent().name).begins_with(key):
				col = colors[key]
		var m := StandardMaterial3D.new()
		m.albedo_color = col
		m.roughness = 0.9
		m.cull_mode = BaseMaterial3D.CULL_DISABLED
		for i in (mi as MeshInstance3D).mesh.get_surface_count():
			(mi as MeshInstance3D).set_surface_override_material(i, m)


## FBX scenes come back with ImporterMeshInstance3D nodes, which don't render;
## swap each for a regular MeshInstance3D.
func _bake_importer_meshes(scene: Node) -> void:
	for n in scene.find_children("*", "ImporterMeshInstance3D", true, false):
		var imi := n as ImporterMeshInstance3D
		var mi := MeshInstance3D.new()
		mi.name = imi.name
		mi.transform = imi.transform
		mi.mesh = imi.mesh.get_mesh()
		imi.get_parent().add_child(mi)
		imi.get_parent().move_child(mi, imi.get_index())
		for c in imi.get_children():
			c.reparent(mi, false)
		imi.free()


func _bounds(root_node: Node3D) -> AABB:
	var box := AABB()
	var first := true
	for mi in root_node.find_children("*", "MeshInstance3D", true, false):
		var b: AABB = (mi as MeshInstance3D).global_transform * (mi as MeshInstance3D).get_aabb()
		box = b if first else box.merge(b)
		first = false
	return box
