extends SceneTree
## Renders pseudo-3D unit sprites (EW-style figures seen from above at an angle)
## into assets/units/<name>_<dir>.png, one per hex direction (0 = east, then
## counter-clockwise in 60 degree steps, matching Hex.DIRS), plus <name>.json
## with the ground anchor.
## A model is either a procedural builder (tools/models/*.gd) or a ready-made
## glTF/FBX file (.glb/.gltf/.fbx, e.g. from a 3D stock site or an AI generator)
## that is scaled to real size and turned to face +X. Team colour is not baked in: the game draws a
## coloured base ring under each unit.
##
## Needs a GPU context, e.g.:
##   xvfb-run godot --path . --rendering-method forward_plus -s res://tools/render_units.gd [-- t72]
## One-off render of a downloaded model (writes assets/units/<name>.png):
##   ... -s res://tools/render_units.gd -- --name=t72 --file=/path/t72.glb --length=9.5 --yaw=0
## Large preview image instead of the game sprite: add --preview=/path/out.png
## Try another camera angle: --elevation=55 (degrees above the horizon)

const SUPERSAMPLE := 4
const OUT_SIZE := Vector2i(320, 320)  # square: a vehicle may point any way
const DIRECTIONS := 6
const OUT_DIR := "res://assets/units/"
## file: builder script or glTF; length_m: real length (glTF is scaled to it);
## yaw: extra turn in degrees so the glTF's front points to +X;
## roughness: matte level for imported paint (EW-style figures are matte);
## tint: multiplies the paint colour (e.g. to darken a pale texture);
## weathered: add mud, dust, streaks and chipped paint (tools/models/weathered.gdshader).
const MODELS := {
	# Generated by the owner in Meshy AI; the texture is pale sage, tinted to olive.
	"t72": {"file": "res://tools/source_models/t72_meshy.fbx", "length_m": 9.5, "yaw": 180.0,
		"tint": Color(0.5, 0.56, 0.4), "weathered": true},
	"t72_procedural": {"file": "res://tools/models/t72.gd"},
}
const ELEVATION := 65.0  # camera angle above the horizon
const VIEW_HEIGHT_M := 11.0  # metres visible vertically
const LOOK_AT := Vector3(0, 0.8, 0)

var preview_path := ""
var elevation := ELEVATION


func _initialize() -> void:
	_run.call_deferred()


func _run() -> void:
	var only: Array[String] = []
	var models := MODELS.duplicate()
	var opts := {}
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--") and "=" in a:
			opts[a.substr(2).get_slice("=", 0)] = a.get_slice("=", 1)
		else:
			only.append(a)
	if opts.has("file"):
		var n: String = opts.get("name", opts["file"].get_file().get_basename())
		models[n] = {"file": opts["file"], "length_m": float(opts.get("length", "7.0")),
			"yaw": float(opts.get("yaw", "0")), "roughness": float(opts.get("roughness", "0.85")),
			"tint": Color(opts.get("tint", "ffffff")), "weathered": opts.get("weathered", "0") == "1"}
		only = [n]
	preview_path = opts.get("preview", "")
	var vp := SubViewport.new()
	vp.size = OUT_SIZE * SUPERSAMPLE
	vp.transparent_bg = true
	vp.own_world_3d = true
	vp.msaa_3d = Viewport.MSAA_4X
	vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(vp)

	var cam := Camera3D.new()
	cam.projection = Camera3D.PROJECTION_ORTHOGONAL
	cam.size = VIEW_HEIGHT_M
	elevation = float(opts.get("elevation", str(ELEVATION)))
	var e := deg_to_rad(elevation)
	cam.position = Vector3(0, sin(e), cos(e)) * 30.0 + LOOK_AT
	vp.add_child(cam)
	cam.look_at(LOOK_AT)

	var sun := DirectionalLight3D.new()
	# Key light from the upper left, in front of the model.
	sun.light_energy = 1.9
	sun.light_color = Color(1.0, 0.95, 0.85)
	sun.rotation_degrees = Vector3(-52, -45, 0)
	sun.shadow_enabled = true
	sun.shadow_blur = 0.6  # crisp shadows so small parts read
	sun.shadow_bias = 0.02
	sun.shadow_normal_bias = 0.6
	sun.directional_shadow_mode = DirectionalLight3D.SHADOW_PARALLEL_4_SPLITS
	sun.directional_shadow_max_distance = 100.0
	vp.add_child(sun)
	var fill := DirectionalLight3D.new()
	fill.light_energy = 0.4
	fill.light_color = Color(0.75, 0.82, 1.0)
	fill.rotation_degrees = Vector3(-25, 150, 0)
	vp.add_child(fill)

	var env := Environment.new()
	env.background_mode = Environment.BG_CLEAR_COLOR
	var sky := Sky.new()
	sky.sky_material = ProceduralSkyMaterial.new()
	env.sky = sky
	env.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	env.ambient_light_energy = 0.45
	env.tonemap_mode = Environment.TONE_MAPPER_FILMIC
	env.tonemap_exposure = 1.05
	env.ssao_enabled = true
	# Strong, tight ambient occlusion darkens seams, hatches and grilles.
	env.ssao_radius = 0.35
	env.ssao_intensity = 4.5
	env.ssao_power = 1.8
	env.ssao_detail = 1.0
	env.ssao_light_affect = 0.25
	env.adjustment_enabled = true
	env.adjustment_saturation = 0.95
	env.adjustment_contrast = 1.12
	var we := WorldEnvironment.new()
	we.environment = env
	vp.add_child(we)

	# Invisible ground that keeps only the shadow (baked into the sprite as alpha).
	var ground := MeshInstance3D.new()
	var plane := PlaneMesh.new()
	plane.size = Vector2(40, 40)
	ground.mesh = plane
	var gm := StandardMaterial3D.new()
	gm.shadow_to_opacity = OS.get_environment("DEBUG_GROUND") == ""
	gm.albedo_color = Color(0.05, 0.06, 0.03)
	ground.material_override = gm
	vp.add_child(ground)

	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	for model_name in models:
		if only.is_empty() or model_name in only:
			await _render(vp, cam, model_name, models[model_name])
	quit()


func _render(vp: SubViewport, cam: Camera3D, model_name: String, spec: Dictionary) -> void:
	var file: String = spec["file"]
	var model := Node3D.new()
	vp.add_child(model)
	if file.ends_with(".gd"):
		load(file).new().build(model)
	else:
		_add_gltf(model, file, spec.get("length_m", 7.0), spec.get("yaw", 0.0))
		_fix_materials(model, spec.get("roughness", 0.85), spec.get("tint", Color.WHITE),
			spec.get("weathered", false))
	var base := ProjectSettings.globalize_path(OUT_DIR + model_name)
	var frames: Array[Image] = []
	for d in DIRECTIONS:
		model.rotation_degrees.y = _yaw_for_dir(d)
		for i in 4:
			await RenderingServer.frame_post_draw
		var img := vp.get_texture().get_image()
		img.resize(OUT_SIZE.x, OUT_SIZE.y, Image.INTERPOLATE_LANCZOS)
		frames.append(img)
		if preview_path == "":
			img.save_png("%s_%d.png" % [base, d])
	model.queue_free()
	if preview_path != "":
		_save_preview(frames)
		return
	# Where the model's ground origin lands in the sprite, and its scale.
	var anchor := cam.unproject_position(Vector3.ZERO) / SUPERSAMPLE
	var meta := {"anchor": [anchor.x, anchor.y], "px_per_m": OUT_SIZE.y / VIEW_HEIGHT_M,
		"directions": DIRECTIONS}
	var f := FileAccess.open(base + ".json", FileAccess.WRITE)
	f.store_string(JSON.stringify(meta))
	print("rendered ", base, "_0..", DIRECTIONS - 1, ".png  anchor=", anchor)


## Hex direction d points 60*d degrees counter-clockwise from screen-right on the
## flat map. The camera is tilted, so depth is foreshortened by sin(elevation);
## turn the model so its projected heading matches the map direction exactly.
func _yaw_for_dir(d: int) -> float:
	var a := deg_to_rad(60.0 * d)
	return rad_to_deg(atan2(sin(a) / sin(deg_to_rad(elevation)), cos(a)))


## All directions side by side on one image (3 per row), at double size.
func _save_preview(frames: Array[Image]) -> void:
	var w := OUT_SIZE.x * 2
	var h := OUT_SIZE.y * 2
	var sheet := Image.create(w * 3, h * 2, false, Image.FORMAT_RGBA8)
	var order := [2, 1, 0, 3, 4, 5]  # NW NE E / W SW SE reads like a compass
	for i in order.size():
		var img: Image = frames[order[i]].duplicate()
		img.resize(w, h, Image.INTERPOLATE_LANCZOS)
		sheet.blit_rect(img, Rect2i(Vector2i.ZERO, img.get_size()), Vector2i((i % 3) * w, (i / 3) * h))
	sheet.save_png(preview_path)
	print("preview ", preview_path)


## Loads a glTF/FBX, sets it on the ground centred at the origin and scales it so
## its longest horizontal side equals length_m.
func _add_gltf(parent: Node3D, file: String, length_m: float, yaw: float) -> void:
	var fbx := file.get_extension().to_lower() == "fbx"
	var doc: GLTFDocument = FBXDocument.new() if fbx else GLTFDocument.new()
	var state: GLTFState = FBXState.new() if fbx else GLTFState.new()
	var err := doc.append_from_file(ProjectSettings.globalize_path(file), state)
	assert(err == OK, "cannot load " + file)
	var scene := doc.generate_scene(state) as Node3D
	_bake_importer_meshes(scene)
	var pivot := Node3D.new()
	pivot.rotation_degrees.y = yaw
	parent.add_child(pivot)
	pivot.add_child(scene)
	var box := _bounds(parent)
	var s := length_m / maxf(box.size.x, box.size.z)
	pivot.scale = Vector3.ONE * s
	box = _bounds(parent)
	pivot.position -= Vector3(box.get_center().x, box.position.y, box.get_center().z)


## Generated/exported models often arrive with emission and vertex-colour tint
## switched on, which washes the paint out; turn those off and make paint matte.
func _fix_materials(model: Node3D, roughness: float, tint: Color, weathered: bool) -> void:
	for mi in model.find_children("*", "MeshInstance3D", true, false):
		var mesh: Mesh = (mi as MeshInstance3D).mesh
		for i in mesh.get_surface_count():
			var m := mesh.surface_get_material(i) as StandardMaterial3D
			if m == null:
				continue
			if weathered:
				(mi as MeshInstance3D).set_surface_override_material(i, _weathered(m, tint))
				continue
			m.emission_enabled = false
			m.vertex_color_use_as_albedo = false
			m.roughness_texture = null
			m.roughness = roughness
			m.metallic = 0.0
			m.albedo_color = tint


func _weathered(src: StandardMaterial3D, tint: Color) -> ShaderMaterial:
	var sm := ShaderMaterial.new()
	sm.shader = load("res://tools/models/weathered.gdshader")
	sm.set_shader_parameter("albedo_tex", src.albedo_texture)
	var lin := tint.srgb_to_linear()  # match StandardMaterial3D, whose albedo_color is sRGB
	sm.set_shader_parameter("tint", Vector3(lin.r, lin.g, lin.b))
	if src.normal_enabled and src.normal_texture:
		sm.set_shader_parameter("normal_tex", src.normal_texture)
		sm.set_shader_parameter("has_normal", true)
	sm.set_shader_parameter("noise_lo", _noise_tex(11, 0.012, 4))
	sm.set_shader_parameter("noise_hi", _noise_tex(12, 0.05, 5))
	return sm


func _noise_tex(seed_value: int, freq: float, octaves: int) -> ImageTexture:
	var n := FastNoiseLite.new()
	n.seed = seed_value
	n.frequency = freq
	n.fractal_octaves = octaves
	var img := n.get_seamless_image(512, 512)
	img.generate_mipmaps()
	return ImageTexture.create_from_image(img)


## FBX scenes come back with ImporterMeshInstance3D nodes, which don't render;
## swap each for a regular MeshInstance3D.
func _bake_importer_meshes(scene: Node) -> void:
	for n in scene.find_children("*", "ImporterMeshInstance3D", true, false):
		var imi := n as ImporterMeshInstance3D
		var mi := MeshInstance3D.new()
		mi.name = imi.name
		mi.transform = imi.transform
		mi.mesh = imi.mesh.get_mesh()
		imi.get_parent().add_child(mi)
		imi.get_parent().move_child(mi, imi.get_index())
		for c in imi.get_children():
			c.reparent(mi, false)
		imi.free()


func _bounds(root_node: Node3D) -> AABB:
	var box := AABB()
	var first := true
	for mi in root_node.find_children("*", "MeshInstance3D", true, false):
		var b: AABB = (mi as MeshInstance3D).global_transform * (mi as MeshInstance3D).get_aabb()
		box = b if first else box.merge(b)
		first = false
	return box
